### ISSUE TITLE
Potato Peel Options in strategy file

### ISSUE THREAD

**Issue by tjgalvin** [flint-crew/flint#308]
Following the discussion from #305 

I have mocked this up in the `potato_peel` branch, but it is not tested. 

I have changed `T` to `tmp`. 

@ErikOsinga - yes, that is basically right. It will end up being this in the strategy file:

```yaml
version: 0.2
defaults:
  wsclean:
    abs_mem: 100
    local_rms_window: 65
    size: 10128
selfcal:
  0:
    wsclean: {}
    potatopeel:
      direct_subtract: true
      intermediate_peels: true
      # directory for tmp files
      tmp: null
  1:
    wsclean:
      data_column: "EXAMPLE"
    gaincal: {}
```

I set `tmp` to `null` so that the routine that drives the potato peeling will insert its own `tmp` path, with the behavior being what you suggested:

```python
tmp_dir = Path(ms.path.parent) / "peel"
potato_peel_options = potato_peel_options.with_options(tmp=tmp_dir)
```

I have not tested this. Perhaps if you want to you could also write a simple unit test to make sure the getter is getting from an example strategy file as we expect? Not a huge deal as it is going through all the same existing code that is being tested anyway.
